repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python
        stages: [pre-commit]
        files: ^(biblioteca|livros)/.*\.py$

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-black
          - flake8-bugbear
        stages: [pre-commit]
        files: ^(biblioteca|livros)/.*\.py$

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        language: system
        entry: pytest -v
        always_run: true
        pass_filenames: false
        stages: [pre-commit]

  - repo: local
    hooks:
      - id: requirements
        name: requirements
        entry: cmd /c "pip freeze > requirements.txt && git add requirements.txt"
        language: system
        pass_filenames: false
        stages: [pre-commit]
